unit Unit1;
{
	This unit creates XLL add-ins, which are automatically
	generated by Bluesofts XLL Add-ins.
	It performs the following tasks:
		+ Installation
		+ Uninstallation
		+ Adding UDF functions
	Author: Nguyen Duy Tuan - tuanktcdcn@yahoo.com - Tel: (+84)904210337
}
interface

uses Winapi.Windows, Winapi.ActiveX,
     BSXLLAPIs, Variants, StrUtils;

type
	TBSMyXLL = class(TBSXLLAddin)
	public
		procedure OnInstall; override;
		procedure OnUninstall; override;
		procedure OnAddFunctions(AFunctions: TBSFunctions); override;
	end;

implementation

(*
Delphi functions will be mapped to XLL UDF functions
+ The function always returns OleVariant type
+ Parameters are always declared with "const". The data type is always OleVariant
*)

//DELPHI FUNCTION

function MyVlookup(const findValue, array2D, ColIndex: OleVariant): OleVariant; stdcall;
const
  errNA = -2146826246; // #N/A
var I, FirstCol, LastCol: Integer;
  vtmp: Variant;
  resCount: Integer;
  resInts: array of Integer;
begin
  VariantInit(Result); //Important!!!
  {
    Check the validity of the parameters
  }
  resCount := 0;
  for I := VarArrayLowBound(array2D, 1) to VarArrayHighBound(array2D, 1) do //each row in ...
  begin
    vtmp := array2D[I, 1];
    if not VarIsError(vtmp) then
    begin
      if not VarIsStr(vtmp) then
        vtmp := VarAsType(vtmp, varOleStr);
      if ContainsText(vtmp, findValue) then
      begin
        resCount := resCount + 1;
        SetLength(resInts, resCount);
        resInts[resCount - 1] := I; //save found row index
      end;
    end;
  end;
  //Get Result
  if resCount = 0 then //not found
  begin
    TVarData(Result).VType := varError;
    TVarData(Result).VError := errNA;
  end
  else
  if resCount = 1 then //Single value
    Result := array2D[resInts[resCount - 1], ColIndex]
  else
  begin
    //Result is 2D array
    //Create array:
    Result := VarArrayCreate([1, resCount, 1, 1], varVariant);
    resCount := 0;
    for I := Low(resInts) to High(resInts) do
    begin
      resCount := resCount + 1;
      Result[resCount, 1] := array2D[resInts[I], ColIndex];
    end;
  end;

end;

//INSTALL XLL UDF FUNCTION - MAPPING DELPHI FUNCTIONS
procedure TBSMyXLL.OnAddFunctions(AFunctions: TBSFunctions);
var
	fn: TBSFunction;
begin
	AFunctions.Category := 'Delphi XLL Functions';
  fn := AFunctions.Add('MyVlookup', @MyVlookup);
  fn.Function_help := 'The function returns an array of the found results.';
  //fn.FunctionTypes := [ftThreadSafe];
  //Add params
  fn.Params.Add('FindValue', 'This is the search value');
  fn.Params.Add('Array2D', 'It is a 2D array for searching and returning results');
  fn.Params.Add('ColumnIndex', 'Result column position');
end;


{ TBSMyXLL - INSTALL XLL ADD-IN }
procedure TBSMyXLL.OnInstall;
begin
	MessageBoxW(GetActiveWindow, 'XLL Add-In registered successfully!'#13#10 +
																 'XLL created from the "BSXLLAddin" library at www.bluesofts.net',
																 LPWSTR(AddinName),
																 MB_OK + MB_ICONINFORMATION);
end;

procedure TBSMyXLL.OnUninstall;
begin
	MessageBoxW(GetActiveWindow, 'XLL Add-In uninstalled.',
																 LPWSTR(AddinName),
																 MB_OK + MB_ICONWARNING);
end;

initialization
	MyXLLAddin := TBSMyXLL.Create('My Excel XLL Add-in for Lookup',
																 'Author: Nguyễn Duy Tuân - https://bluesofts.net');

finalization

end.