unit Unit1;
{
	This unit creates XLL add-ins, which are automatically 
	generated by "Bluesofts XLL Add-in Builder".
	It performs the following tasks:
		+ Installation
		+ Uninstallation
		+ Adding UDF functions
	Author: Nguyen Duy Tuan - tuanktcdcn@yahoo.com - Tel: (+84)904210337
}
interface

uses Winapi.Windows, Winapi.ActiveX,
     BSXLLAPIs;

type
	TBSMyXLL = class(TBSXLLAddin)
	public
		procedure OnInstall; override;
		procedure OnUninstall; override;
		procedure OnAddFunctions(AFunctions: TBSFunctions); override;
	end;

implementation

(*
Delphi functions will be mapped to XLL UDF functions
+ The function always returns OleVariant type
+ Parameters are always declared with "const". The data type is always OleVariant
*)

function MyName(): OleVariant; stdcall;
begin
	VariantInit(Result); //important!
	Result := 'Nguyễn Duy Tuân';
end;

function MySum(const v1, v2: OleVariant): OleVariant; stdcall;
begin
	VariantInit(Result);
	Result := v1 + v2;
end;

function MyAny(const x: OleVariant): OleVariant; stdcall;
begin
	VariantInit(Result);
	Result := x;
end;

function MyAsync(const Value: OleVariant): OleVariant; stdcall;
begin
	VariantInit(Result);
	Result := Value;
end;

{ TBSMyXLL - INSTALL XLL ADD-IN }
procedure TBSMyXLL.OnInstall;
begin
	MessageBoxW(GetActiveWindow, 'XLL Add-In registered successfully!'#13#10 +
																 'XLL created from library "BSXLLAddin" on www.bluesofts.net',
																 LPWSTR(AddinName),
																 MB_OK + MB_ICONINFORMATION);
end;

procedure TBSMyXLL.OnUninstall;
begin
	MessageBoxW(GetActiveWindow, 'Add-In XLL removed.',
																 LPWSTR(AddinName),
																 MB_OK + MB_ICONWARNING);
end;

//INSTALL XLL UDF FUNCTION - MAPPING DELPHI FUNCTIONS
procedure TBSMyXLL.OnAddFunctions(AFunctions: TBSFunctions);
var
	fn: TBSFunction;
begin
	AFunctions.Category := 'Delphi XLL Functions';
	//Adding UDF functions to XLL - Mapping with Delphi functions
	//1. Add UDF function MyName()
	fn := AFunctions.Add('MyName', @MyName);
	fn.Function_help := 'Function returns unicode string.';
	//-----------------

	//2. Add UDF function GetAny()
	fn := AFunctions.Add('MyAny', @MyAny);
	fn.Function_help := 'Function returns one or array of values ​​depending on the parameters passed.';
		//Add parameters to the function.
	fn.Params.Add('Value', 'is any one or array of values');
	//-----------------

	//3. Add UDF function MySum()
	fn := AFunctions.Add('MySum', @MySum);
	fn.Function_help := 'Function returns the sum of a + b.';
		//Add parameters to the function.
	fn.Params.Add('A', 'Enter number > 0');
	fn.Params.Add('B', 'Enter numbers > 0 and < 100');
	//-----------------

	//4. Add UDF function MyFunc()
	fn := AFunctions.Add('MyFunc', @MySum);
	fn.Function_help := 'Function that returns the sum of a + b.';
		//Add parameters to the function.
	fn.Params.Add('A', 'Enter a number > 0');
	fn.Params.Add('B', 'Enter a number > 0 and < 100');
	//-----------------

	//5. Add UDF function MyAsync()
	fn := AFunctions.Add('MyAsync', @MyAsync, True);
	fn.Function_help := 'Function that runs asynchronously.';
		//Add parameters to the function.
	fn.Params.Add('Value', 'A single value or an array of arbitrary values');
	//-----------------
end;

initialization
	MyXLLAddin := TBSMyXLL.Create('My Excel XLL Add-in',
																 'Author: Nguyễn Duy Tuân - https://bluesofts.net');

finalization

end.